In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10).reshape(3,3)

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.linspace(1,10,12).reshape(3,4)

array([[ 1.        ,  1.81818182,  2.63636364,  3.45454545],
       [ 4.27272727,  5.09090909,  5.90909091,  6.72727273],
       [ 7.54545455,  8.36363636,  9.18181818, 10.        ]])

In [5]:
np.linspace(1,10,12,dtype=int).reshape(3,4)

array([[ 1,  1,  2,  3],
       [ 4,  5,  5,  6],
       [ 7,  8,  9, 10]])

In [6]:
np.random.rand(3,3)

array([[0.39785751, 0.65730432, 0.16890266],
       [0.02146869, 0.16524579, 0.20843628],
       [0.98701754, 0.77573071, 0.69216023]])

In [7]:
np.random.rand(3,3)*10


array([[9.97033733, 4.33784725, 8.30386684],
       [1.78098668, 3.74174556, 1.54515897],
       [1.57663703, 7.12705271, 6.5730431 ]])

In [8]:
zeros = np.zeros((3,3))

In [9]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
a = np.arange(1,9).reshape(2,4)
b = np.arange(9,17).reshape(2,4)

In [29]:
a


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
b

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
a+b

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [32]:
a*b

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

In [34]:
c = np.arange(1,9).reshape(4,2)

In [37]:
b**2

array([[ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [38]:
10*np.sin(a)

array([[ 8.41470985,  9.09297427,  1.41120008, -7.56802495],
       [-9.58924275, -2.79415498,  6.56986599,  9.89358247]])

In [39]:
a<35

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
a<2

array([[ True, False, False, False],
       [False, False, False, False]])

In [41]:
a<1

array([[False, False, False, False],
       [False, False, False, False]])

In [43]:
a@c

array([[ 50,  60],
       [114, 140]])

In [47]:
x = np.random.rand(3,3)
x

array([[0.07701506, 0.58475599, 0.45095166],
       [0.53009856, 0.18921695, 0.3324053 ],
       [0.08064491, 0.1238416 , 0.67668101]])

# indexing and slicing 

In [55]:
myarray = np.arange(1,17,dtype=int).reshape(4,4)

In [56]:
myarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
myarray[2]

array([ 9, 10, 11, 12])

In [58]:
myarray[2][2]

np.int64(11)

In [59]:
myarray[2,2]

np.int64(11)

In [60]:
myarray[1,1]

np.int64(6)

In [61]:
myarray[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
myarray[1:3,3]

array([ 8, 12])

In [63]:
myarray[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [64]:
myarray[2:4,2:4].flatten()

array([11, 12, 15, 16])

In [75]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

In [76]:
a

array([[3., 7.],
       [9., 6.]])

In [77]:
np.vstack((a,b))

array([[3., 7.],
       [9., 6.],
       [8., 2.],
       [0., 1.]])

In [78]:
np.hstack((a,b))

array([[3., 7., 8., 2.],
       [9., 6., 0., 1.]])

In [79]:
np.hsplit(a,2)

[array([[3.],
        [9.]]),
 array([[7.],
        [6.]])]

In [81]:
d = np.arange(1,10)
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
bool_arr = d%2 == 0
bool_arr

array([False,  True, False,  True, False,  True, False,  True, False])

In [85]:
e = np.arange(10,19)
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [86]:
e[bool_arr]

array([11, 13, 15, 17])

In [88]:
f = np.arange(1,5).reshape(2,2)
f

array([[1, 2],
       [3, 4]])

In [90]:
f.transpose()

array([[1, 3],
       [2, 4]])

In [91]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
np.diagonal(f)

array([1, 4])

In [93]:
np.trace(f)

np.int64(5)